### ISSUE TITLE
Chest spewn at 0, when dying at <0

### ISSUE THREAD

**Issue by kawashirov** [defNotPau/SimpleDeathChest#1]
Hello there! Nice plugin, good job.

But I noticed an issue: on modern Minecraft versions, when player dies at y < 0 the chest respawns around y = 0.
This is especially problematic when dying deep inside caves.

As I heard, there was api to check vertical bounds of the world, so you can replace 0 on this check with that bound. 🤷‍♂️
![image](https://github.com/user-attachments/assets/c54796ae-1a9f-472c-aaf0-9232fd60b5c0)

**Comment by defNotPau** [comment]
Hi, i think the error is fixed, its currently only for the 1.2.x branch as I don't have time to make the change into main. The Modrinth version with the fix will probably be out tomorrow. Thank you so much for pointing this out :D

(I used WorldInfo.getMinHeight())
![image](https://github.com/user-attachments/assets/72063217-7014-4c7f-b119-bc2bde24f543)
